name: Singularity Build

on:
  pull_request:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

env:
  SINGULARITY_VERSION: 3.6.4
  SINGULARITY_USERNAME: jakebolewski
  SINGULARITY_COLLECTION: clima
  SINGULARITY_RECIPE: Documenter
  SINGULARITY_OUTPUT_CONTAINER: documenter.sif

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Install Dependencies
      run: |
        sudo apt-get update || true
        sudo apt-get install -y \
          build-essential \
          libssl-dev \
          uuid-dev \
          libgpgme11-dev \
          squashfs-tools \
          libseccomp-dev \
          pkg-config

    - name: Install Singularity
      env:
        GOPATH: /tmp/go
      run: |
        mkdir -p $GOPATH
        sudo mkdir -p /usr/local/var/singularity/mnt && \
        mkdir -p $GOPATH/src/github.com/sylabs && \
        cd $GOPATH/src/github.com/sylabs && \
        wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
        tar xzv && \
        cd singularity && \
        ./mconfig -p /usr/local && \
        make -C builddir && \
        sudo make -C builddir install          
          
    - name: Check out code for the container build
      uses: actions/checkout@v1

    - name: Build Container
      run: |
       if [ -f "${SINGULARITY_RECIPE}" ]; then
            sudo -E singularity build ${SINGULARITY_OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
       else
           echo "${SINGULARITY_RECIPE} is not found."
           echo "Present working directory: $PWD"
           ls
       fi

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "${SINGULARITY_OUTPUT_CONTAINER}"
        path: "${SINGULARITY_OUTPUT_CONTAINER}"
        retention-days: 3

    - name: Deploy Container
      if: startsWith( github.ref, 'refs/tags/')
      env:
        SYLABS_TOKEN: ${{ secrets.SYLABS_TOKEN }}
      run: |
        RELEASE_VERSION="${GITHUB_REF#refs/*/}"
        printf '%s\n' "$SYLABS_TOKEN" | singularity remote login
        singularity push -U \
          "${SINGULARITY_OUTPUT_CONTAINER}" \
          "library://${SINGULARITY_USERNAME}/${SINGULARITY_COLLECTION}/${SINGULARITY_OUTPUT_CONTAINER}:${RELEASE_VERSION}"
